sudo: false
language: python
python:
  - 2.7
  - 3.5
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
install:
  - "pip install tox"
script:
  - tox
after_success:
  - coveralls
