language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=geobuf -m py.test
after_success:
  - coveralls
sudo: false
