sudo: false
language: python
python:
  - 2.7
  - 3.5
addons:
  apt:
    packages:
      - pandoc
install:
    - "pip install pytest-cov"
script:
  - python setup.py --long-description
  - python -m pytest --cov geobuf --cov-report term-missing
after_success:
  - coveralls
deploy:
  on:
    tags: true
  provider: pypi
  user: mapboxci
  distributions: "sdist bdist_wheel"
